FROM python:3.6-alpine

COPY . /queue
WORKDIR /queue

RUN apk add gcc libc-dev linux-headers
RUN pip install -U pip
RUN pip install -r requirements.txt

ENTRYPOINT ["celery", "worker", "--app=celery_worker.app", "--loglevel=info"]